# Generated by Django 4.0.4 on 2025-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_postulacion', models.CharField(max_length=100)),
                ('formulario', models.FileField(upload_to='formularios/')),
                ('rut_organizacion', models.FileField(upload_to='ruts/')),
                ('ci_representante', models.FileField(upload_to='cis/')),
                ('certificado_personalidad', models.FileField(upload_to='certificados_personalidad/')),
                ('certificado_fondos', models.FileField(upload_to='certificados_fondos/')),
                ('cuenta_corriente', models.FileField(upload_to='cuentas_corrientes/')),
                ('acreditacion_propiedad', models.FileField(blank=True, null=True, upload_to='acreditaciones/')),
                ('aportes_propios', models.FileField(blank=True, null=True, upload_to='aportes_propios/')),
                ('aportes_terceros', models.FileField(blank=True, null=True, upload_to='postulaciones/')),
                ('cotizaciones', models.JSONField(default=list)),
                ('otros_documentos', models.JSONField(default=list)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('es_funcionario', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
