# Generated by Django 4.0.4 on 2025-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
